### ISSUE TITLE
Wrong npm link

### ISSUE THREAD

**Issue by Armanoide** [KjellConnelly/react-native-shared-group-preferences#1]
In the ***Getting started*** of the readme you display the wrong link

it should be `npm install react-native-shared-group-preferences --save` not `npm install react-native-react-native-shared-group-preferences --save`

**Comment by KjellConnelly** [comment]
Haha good point :) the create-library module I used made a few mistakes :D will fix in ten mins.

**Comment by Armanoide** [comment]
Great thanks and good work !
