### ISSUE TITLE
pod install not working / null is not an object (evaluating 'RNReactNativeSharedGroupPreferences.getItem')

### ISSUE THREAD

**Issue by edgarosovel** [KjellConnelly/react-native-shared-group-preferences#11]
So I'm getting 
`"null is not an object (evaluating 'RNReactNativeSharedGroupPreferences.getItem')"`
So after seeing the closed issues I found that I should  

> Link the library properly under 'Link binary with Libraries' (libRNReactNativeSharedGroupPreferences.a) #3 

The problem is that even after` react-native link` and `pod install` libRNReactNativeSharedGroupPreferences.a is not popping up in the workspace libraries. What am I missing?

**Comment by KjellConnelly** [comment]
Not exactly sure how pod works (don't use it myself), but you can open Xcode and:

navigate to `Libraries > RNReactNativeSharedGroupPreferences.xcodeproj > Products > libRNReactNativeSharedGroupPreferences.a` and drag this into `Build Phases > Link Binary with Libraries`

**Comment by edgarosovel** [comment]
Ugh, that was so much easier! I ended up forking the repo and modifying so I it could use `pod install`: [Repo](https://github.com/edgarosovel/react-native-shared-group-preferences)
Anyways, both methods work just fine. Thank you very much for this repo btw, helped me a lot :)

**Comment by panutat** [comment]
Doesn't seem like the steps apply to latest xcode anymore. Any suggestion? Thank you
