### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by antony-meunier** [KjellConnelly/react-native-shared-group-preferences#5]
Hello,
I have an issue with android when I try to set up multiple items like this : 

this._setStorageA('Avalue');
this._setStorageB('Bvalue');

Then when I try to get my values, on IOS, everything is fine, but on Android, everything is overrided by the last value

**Comment by KjellConnelly** [comment]
Hi Derpidy,

I think it’s because there is only one file being saved to. So if you want multile values, you just need to provide a JSON object as the entire file will be rewritten every time you save. It’s not ideal, but that’s the solution that fit my problem when I made this module.
