### ISSUE TITLE
IOS error with getItem

### ISSUE THREAD

**Issue by andersonqi** [KjellConnelly/react-native-shared-group-preferences#8]
Hi there 

I'm using [react-native-share-extension](https://github.com/alinz/react-native-share-extension)

`await SharedGroupPreferences.getItem('sample', appGroupIdentifier, { useAndroidSharedPreferences:true });`

I get this error when I trying to get value from Shared Extension

`[TypeError: undefined is not an object (evaluating 'RNReactNativeSharedGroupPreferences.getItem')`

**Comment by galikvalkin** [comment]
@andersonqi 

if it is still actual

check - if you have linked this module in Xcode to Share Extension
